packages:
  - backend
  - frontend
  - shared/*

onlyBuiltDependencies:
  - '@prisma/engines'
  - '@sentry-internal/node-cpu-profiler'
  - esbuild
  - msgpackr-extract
  - nx
  - prisma
  - sharp
  - unrs-resolver
  - '@prisma/client'
  - better-sqlite3
